### ISSUE TITLE
Støtte flere aktivitetstyper

### ISSUE THREAD

**Issue by mathiamo** [TreshLaps/Activities#10]
Burde kanskje for filtrere ut irrelevante aktivitetstyper som NordicSki, Elliptical, osvsov

**Comment by hallatore** [comment]
Jeg vil helst at vi støtter en del typer, men spisser mot gitte typer.
F.eks for OSI Tri så vil Svømming, Ride og VirtualRide være gull. For min egen del er NordicSki konge 😍

Men, vi kan godt filtrere ut en del økter under Activities.

Forslag til økter: (Noen flere?)
- Run
- Ride
- VirtualRide
- Svimming
- NordicSki (Vi bor i norge tross alt 😅)

**Comment by fyksen** [comment]
Når vi først er igang vil jeg også ha med elliptical.

**Comment by fyksen** [comment]
Maybe someone would like elliptical, but this will probably be implemented when a developer gets injured..

![image](https://user-images.githubusercontent.com/4790633/213470762-f6020016-74cf-4076-88c5-7f2adcfa91ed.png)
