### ISSUE TITLE
Forslag på sporing av inneløping

### ISSUE THREAD

**Issue by fyksen** [TreshLaps/Activities#12]
De fleste har ikke foot pod. Og de fleste food pods er ikke nøyaktig nok til å brukes som sporing.

De fleste laper, for å få tiden man brukte på runden.
En fin måte å få farten på, kan være å få brukeren til å skrive inn hvor lang runden var selv.

| Lap number  | Time on Lap |  Distance on lap |  Is this a intervall lap? | Is the distance correct? |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Lap 1       | 15:05  | 3,45k | [ ]   |  [x]
| Lap 2       | 3:30  |  0,97k| [x]    | [x]

Når man haker bort at den er korrekt, så blir man spurt om lap distance:

| Lap number  | Time on Lap |  Distance on lap |  Is this a intervall lap? | Is the distance correct? |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Lap 1       | 15:05  | 3,45k | [ ]   |  [x]
| Lap 2       | 3:30  |  [Input distance]| [x]    | [ ]

**Comment by Harbo96** [comment]
> De fleste har ikke foot pod. Og de fleste food pods er ikke nøyaktig nok til å brukes som sporing.
> 
> De fleste laper, for å få tiden man brukte på runden.
> En fin måte å få farten på, kan være å få brukeren til å skrive inn hvor lang runden var selv.
> 
> Lap number	Time on Lap	Distance on lap	Is this a intervall lap?	Is the distance correct?
> Lap 1	15:05	3,45k	[ ]	[x]
> Lap 2	3:30	0,97k	[x]	[x]
> Når man haker bort at den er korrekt, så blir man spurt om lap distance:
> 
> Lap number	Time on Lap	Distance on lap	Is this a intervall lap?	Is the distance correct?
> Lap 1	15:05	3,45k	[ ]	[x]
> Lap 2	3:30	[Input distance]	[x]	[ ]

For bislett kan man legge inn en feature hvor man skal skrive hvor mange runder lappen var. 1runde=546m og da vil man automatisk kunne få korrigert pace.

**Comment by Harbo96** [comment]
> ![image](https://user-images.githubusercontent.com/4790633/112622467-5a9e6500-8e2b-11eb-888a-71d54dc94139.png)
> Kan kanskje bruke denne taggen, for å finne ut hvilke økter man skal gjøre det på. Problemet med det, er at om man løper på innendørsbane (typisk bislett), så vil man kanskje ikke merke det som treadmill.
> 
> Alternativt, kunne man brukt en eller annen emoji i description for å trigge det også. 🏘️
> 
> Jeg finner ikke noe referanse til threadmill taggen i stravadokumentasjonen:
> https://developers.strava.com/docs/reference/

Vanskeligere å korrige møllefart enn fart på bislett. På bislett vet vi nøyaktig lengden på dragene (hvis vi vet antall runder, eller det oppgis draglengde), mn mølla kan være ukalibrert (som er svært vanlig spesielt på høyere hastigheter). Det kan derfor være i praksis umulig å vite egentlig fart. Mulig mølleløping derfor ikke skal tas med for utregning av gjs pace per uke. Tiden på mølle vil være riktig, så denne kan vi bruke, og lengden kan vi oppgi (og eventuelt korrigere), fordi feilmarginen vil mest sannsynlig ikke ha så stor betydning.

**Comment by fyksen** [comment]
Got done in https://github.com/TreshLaps/Activities/commit/7f6021a8f907783f646c49fdda0c7a0fd60b6d86
