### ISSUE TITLE
Tag activities with feeling

### ISSUE THREAD

**Issue by mwarvik** [TreshLaps/Activities#15]
Subjective feeling on how it felt compared to lactate/intensity.

Feeling is divided into "lett", "vanlig" and "tung" and is parsed from Strava description with ex. "Følelse: lett".

**Comment by fyksen** [comment]
Tre forskjellige følelser:
Lett, vanlig, tung.

Strava kaller det "Perceived Exertion", men det ser ikke ut til at det er noe dokumentasjon på det i APIen deres, men vi kan polle det fra description (på lik linje med laktat), men det skal også kunne settes direkte i appen. (kanskje ikke vits i å gjøre ennå?).
Lenkes til økt, ikke til lap.

Regex blir noe sånn?
```
[\n\r][ \t]*Følelse:[ \t]*([^\n\r]*)
[\n\r][ \t]*følelse:[ \t]*([^\n\r]*)
```
Også må man kanskje ha noe for å fjerne duster som meg som noen ganger skriver "Følelse: vanlig." istedenfor "Følelse: vanlig"

**Comment by fyksen** [comment]
Done.
Supported data is:
Følelse: lett|vanlig|tung
